using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Windows.Data.Json;
using Windows.Storage;

namespace CherryProject.Service
{
	public class CountryProvider
	{
		private static CountryProvider _instance;

		public static CountryProvider Instance { get => _instance ?? (_instance = new CountryProvider()); }
		
		private readonly List<string> _regionList;

		public List<string> RegionList => _regionList;

		public CountryProvider()
		{
			_regionList = new string[]{
				"Afghanistan",
				"Albania",
				"Algeria",
				"American Samoa",
				"Andorra",
				"Angola",
				"Anguilla",
				"Antarctica",
				"Antigua And Barbuda",
				"Argentina",
				"Armenia",
				"Aruba",
				"Australia",
				"Austria",
				"Azerbaijan",
				"Bahamas",
				"Bahrain",
				"Bangladesh",
				"Barbados",
				"Belarus",
				"Belgium",
				"Belize",
				"Benin",
				"Bermuda",
				"Bhutan",
				"Bolivia",
				"Bosnia And Herzegowina",
				"Botswana",
				"Bouvet Island",
				"Brazil",
				"British Indian Ocean Territor",
				"Brunei Darussalam",
				"Bulgaria",
				"Burkina Faso",
				"Burundi",
				"Cambodia",
				"Cameroon",
				"Canada",
				"Cape Verde",
				"Cayman Islands",
				"Central African Republic",
				"Chad",
				"Chile",
				"China",
				"Christmas Island",
				"Cocos (Keeling) Islands",
				"Colombia",
				"Comoros",
				"Congo",
				"Cook Islands",
				"Costa Rica",
				"Cote D'Ivoire",
				"Croatia (Local Name: Hrvatska)",
				"Cuba",
				"Cyprus",
				"Czech Republic",
				"Denmark",
				"Djibouti",
				"Dominica",
				"Dominican Republic",
				"East Timor",
				"Ecuador",
				"Egypt",
				"El Salvador",
				"Equatorial Guinea",
				"Eritrea",
				"Estonia",
				"Ethiopia",
				"Falkland Islands (Malvinas)",
				"Faroe Islands",
				"Fiji",
				"Finland",
				"France",
				"French Guiana",
				"French Polynesia",
				"French Southern Territories",
				"Gabon",
				"Gambia",
				"Georgia",
				"Germany",
				"Ghana",
				"Gibraltar",
				"Greece",
				"Greenland",
				"Grenada",
				"Guadeloupe",
				"Guam",
				"Guatemala",
				"Guinea",
				"Guinea-Bissau",
				"Guyana",
				"Haiti",
				"Heard And Mc Donald Islands",
				"Holy See (Vatican City State)",
				"Honduras",
				"Hong Kong",
				"Hungary",
				"Icel And",
				"India",
				"Indonesia",
				"Iran (Islamic Republic Of)",
				"Iraq",
				"Ireland",
				"Israel",
				"Italy",
				"Jamaica",
				"Japan",
				"Jordan",
				"Kazakhstan",
				"Kenya",
				"Kiribati",
				"Korea, Dem People'S Republic",
				"Korea, Republic Of",
				"Kuwait",
				"Kyrgyzstan",
				"Lao People'S Dem Republic",
				"Latvia",
				"Lebanon",
				"Lesotho",
				"Liberia",
				"Libyan Arab Jamahiriya",
				"Liechtenstein",
				"Lithuania",
				"Luxembourg",
				"Macau",
				"Macedonia",
				"Madagascar",
				"Malawi",
				"Malaysia",
				"Maldives",
				"Mali",
				"Malta",
				"Marshall Islands",
				"Martinique",
				"Mauritania",
				"Mauritius",
				"Mayotte",
				"Mexico",
				"Micronesia, Federated States",
				"Moldova, Republic Of",
				"Monaco",
				"Mongolia",
				"Montserrat",
				"Morocco",
				"Mozambique",
				"Myanmar",
				"Namibia",
				"Nauru",
				"Nepal",
				"Netherlands",
				"Netherlands Ant Illes",
				"New Caledonia",
				"New Zealand",
				"Nicaragua",
				"Niger",
				"Nigeria",
				"Niue",
				"Norfolk Island",
				"Northern Mariana Islands",
				"Norway",
				"Oman",
				"Pakistan",
				"Palau",
				"Panama",
				"Papua New Guinea",
				"Paraguay",
				"Peru",
				"Philippines",
				"Pitcairn",
				"Poland",
				"Portugal",
				"Puerto Rico",
				"Qatar",
				"Reunion",
				"Romania",
				"Russian Federation",
				"Rwanda",
				"Saint K Itts And Nevis",
				"Saint Lucia",
				"Saint Vincent, The Grenadines",
				"Samoa",
				"San Marino",
				"Sao Tome And Principe",
				"Saudi Arabia",
				"Senegal",
				"Seychelles",
				"Sierra Leone",
				"Singapore",
				"Slovakia (Slovak Republic)",
				"Slovenia",
				"Solomon Islands",
				"Somalia",
				"South Africa",
				"South Georgia , S Sandwich Is",
				"Spain",
				"Sri Lanka",
				"St. Helena",
				"St. Pierre And Miquelon",
				"Sudan",
				"Suriname",
				"Svalbard, Jan Mayen Islands",
				"Sw Aziland",
				"Sweden",
				"Switzerland",
				"Syrian Arab Republic",
				"Taiwan",
				"Tajikistan",
				"Tanzania, United Republic Of",
				"Thailand",
				"Togo",
				"Tokelau",
				"Tonga",
				"Trinidad And Tobago",
				"Tunisia",
				"Turkey",
				"Turkmenistan",
				"Turks And Caicos Islands",
				"Tuvalu",
				"Uganda",
				"Ukraine",
				"United Arab Emirates",
				"United Kingdom",
				"United States",
				"United States Minor Is.",
				"Uruguay",
				"Uzbekistan",
				"Vanuatu",
				"Venezuela",
				"Viet Nam",
				"Virgin Islands (British)",
				"Virgin Islands (U.S.)",
				"Wallis And Futuna Islands",
				"Western Sahara",
				"Yemen",
				"Zaire",
				"Zambia",
				"Zimbabwe"
			}.ToList();
		}
	}
}
